### ISSUE TITLE
Masks

### ISSUE THREAD

**Issue by mattarderne** [andrejbauer/social-distancing-simulator#8]
This is a great tool. 

Would you consider adding a variable to include mask usage (% people using masks, % effectiveness of masks)? 
 
https://www.washingtonpost.com/outlook/2020/03/28/masks-all-coronavirus/

**Comment by andrejbauer** [comment]
Sorry, I am not going to extend the simulator because it's not really suitable for any kind of realistic simulation. It's designed to show one thing well, namely the idea that social distancing flattens the curve. You are of course free to fork the project and do it yourself.
